name: Run UIC_MIS_ROBBER

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your username'
        required: true
      password:
        description: 'Enter your password'
        required: true
        secret: true
      courses:
        description: 'Enter the course names (comma-separated)'
        required: true
      start_time:
        description: 'Enter the start time'
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout UIC_MIS_ROBBER repository
      uses: actions/checkout@v2
      with:
        repository: henrykingcn/UIC_MIS_ROBBER
        path: UIC_MIS_ROBBER

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        # Install other dependencies here if necessary
        # e.g., pip install -r UIC_MIS_ROBBER/requirements.txt

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.182/linux64/chrome-linux64.zip
        unzip chrome-linux64.zip -d chrome
        sudo mv chrome/chrome-linux64 /usr/local/bin/chrome
        sudo ln -s /usr/local/bin/chrome/chrome /usr/local/bin/google-chrome
        sudo chmod +x /usr/local/bin/google-chrome
        google-chrome --version

    - name: Install ChromeDriver
      run: |
        wget https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.182/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip -d chromedriver
        sudo mv chromedriver/chromedriver-linux64 /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version

    - name: Run Python script
      env:
        USERNAME: ${{ github.event.inputs.username }}
        PASSWORD: ${{ github.event.inputs.password }}
        COURSES: ${{ github.event.inputs.courses }}
        START_TIME: ${{ github.event.inputs.start_time }}
      run: |
        python UIC_MIS_ROBBER/START_ROBBER.py
